# Generated by Django 6.1.1 on 2026-10-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='license_DB',
            fields=[
                ('license_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('Dob', models.DateField()),
                ('issueDate', models.DateField()),
                ('fathersName', models.CharField(max_length=20)),
                ('bloodgrp', models.CharField(max_length=5)),
                ('address', models.TextField()),
            ],
        ),
    ]
